language: objective-c
osx_image: xcode7.2
xcode_project: OtsimoSDK.xcodeproj
xcode_scheme: <SCHEME_PLACEHOLDER>
xcode_sdk: iphonesimulator9.2
env:
  global: 
    - FRAMEWORK_NAME=OtsimoSDK
before_install:
  - brew update
  - brew install carthage
before_script:
  - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive OtsimoSDK OtsimoApiGrpc Locksmith Haneke gRPC Realm RealmSwift