language: objective-c
osx_image: xcode8.0
xcode_project: OtsimoSDK.xcodeproj
xcode_scheme: OtsimoSDK
xcode_sdk: iphonesimulator10.0
env:
  global:
  - FRAMEWORK_NAME=OtsimoSDK
  - secure: HUA1bfNvOLaHYtp8qZG97jxv58re89rcxZszNATeXaVmRTjOuEekKaxpRjsZosfZncI2a/oTcEXPaKHPkOcO4RuW4/7KitnWN8N5hHZYh0pMYRBjUy2SokF9XxzmuWrkVPxAhQK0vKy/tCQx2PQZMh8+1m1B1WwMu0kZhUth+Ow+jHkgWCz+3sUJjpFdSv5hVIs4Cfl0OUQQM1qVWW/5jrfR3QVuPJbNwE6LbGB9yFCuX/7LjhgjgmBmJnKk2o+ATzEkz8zUBVlWxkK5HOwjKUwiOTFvpxQ+sXKM4UwjO7Hps/7ZRc7vLPtNZG4ZFQ8JMFxE72x1NvAq5X1YOGCkI6w4srJN9iEVWbw1rxHx0z55OksE2P+GBNieLZSIuIlFTkfT+WF/LeUVq5MzxuYBmmLXD6pf8rYELmCuvDAuy5c95Nju8bX07uZv/vX3U4gDrP/O0a50ErergamQ8qf74JPzkkhMg5T8dK83C7M4rX5cqWCubX0QY7zjbTTWAzKbyNR59RnoRA4FnczkAeeuasZ0WdOHUQX/AqbeX61/8GdR1vCPhWDnU1y6WyOwRbX/Oye3f3hrOVwA9E8Vit5FPV32JWDhaGR8VMaaVJp1yOrEZf9AsfvMDnZHWFhcy4cmcndUNoqZxVhyJtMLcWBg9FijpdB8sDdTgBZS1eSyCNs=
script: sh script/build.sh
before_script:
- carthage bootstrap --platform ios
before_deploy:
- carthage archive OtsimoSDK
deploy:
  provider: releases
  api_key:
    secure: jcXHdQQaZowOmW74t4LxZDt0aqn2JHOdo4A8xkInJecwxUmPnT424bXf2VxA1ZxPvBAXQMvSjCVfOMULk5ZmC7pUm5+CeWmr83u2u9kVxOuryPjkHXVerqY+OyoU24ytgFo2CiFYt2T1WFi9IDnKiW6k0nTvD4IWhB8PQaVZTraRQ/xfsn7MB51j5WN5/IZxl4UI3YGIDOsi3F/vq2PScOk0v4spHVWxSTaiFO+/V9WR+IrwFrbG69f7W+ChVbD0rXglHec2FozIEtu4wVEpteOFGgxglftFS2o9flt2IqOQYh6YM19xBx3QhC1slzhOHrtNd5afGs4R1rWQAkj8P5q6BPiiFkJfRt7QyphJI25EnrDsgJGI9+B7S96JxG4cA0FCNK1Dz89StFGjVocAHRatiUsloVrjeuwf07lirZmGHlY9O2pRtkjH/23C+rAhsqoiZxNlfA1mimLYuQ7wN6UHHi8VTh70xbRLjl2f3EsbYcYo7WkMQ29T3KvCYGfaSX8VqrhTA5b+VmzIVqx2p6aKzFqe0ITFjrBDUOJ02LZJNSPW+CEa6I1WuqBOgmw6FkOQvI9fIfpHhOgH7pGr7DkE2SkEPd3IbqOepJLzqSfZdfO/WxLjPQsuO3BBD+L2AM3OWx6WGVu9HKa3abniHu6wLCX0UR5pPBGWVraATH8=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: otsimo/otsimo-ios-sdk
    tags: true
notifications:
  email: false
  slack:
    secure: dr6u+Xjksz3y16UsSuXdCL9Ad4BJIVLGvexNLJrv7nsPvtPKfN9MYh0MHKEzK7y7Oieu/G89pWUKp+htYwFsDB7aJdFzXXJK8RpTEEVlaTtxz3rf3JG3XWdxrZQtj95eL9va9Eb/GK+0FMhb6lfXjaVYjbO5MCC0J6U9lXwxXhhPI6qFnDbxYuT7xa/8AdMleI5Ww3RsbhBeHOswd37IM0f0cR3TtcNLctrxC+45KKJp7QoJjuiDFlmaX4x20WAPNhRvnkVfTSFc6vUwBfqhRyGwwChsI1jrNhwcNEonlAtY/ah/we48V6GzZstWCUjgKTIsvl+QQV3hFmlv/2RIa1qO6qHhkW7JxxjK6vr6w3feYV8Aa8LJDsY90qVgm8420NfNTKhGxFiyo7K+4MyOvCWfaF/sbiw99Mp1C/3ZBzJXG8X2TTxn2F7ytcqZVOygQlnsd/M4W5dDMwINwlO4msaXRV8lWfdjBkx8m4Ow20RfnWC6NjRa9LmZ7VUj78IArLtXPnNG14d6Vlz5zR9hwwOEiut1Weqit8c6mUVE2hPdxSX2Z3y9QSlhTfKSUPB6fSjU9cvzf/4X6F/3veCtn/gMv4RCNU/57Mp6dR4p995Vw0O5t6yMmOAQu2o+5tCu1nwpCqwaYcjh5eWgAr8MmCJqB/t8TEsVY20F53LG37Y=
