// Code generated by protoc-gen-grpc-swift
// DO NOT EDIT!
import SwiftProtobuf
import GRPCClient


public class ApiService: GrpcProtoService {

    public convenience init(host: String) {
        self.init(host: host, packageName: "apipb", serviceName: "ApiService")
    }

    public func addProfile(_ request: Apipb_Profile,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "AddProfile",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func getProfile(_ request: Apipb_GetProfileRequest,
                           handler: @escaping (Apipb_Profile?, Error?) -> Void) -> GrpcProtoCall<Apipb_Profile> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Profile, error)
        }
        return RPC(method: "GetProfile",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Profile.self,
                   responsesWriteable: writable!)
    }
	
    public func updateProfile(_ request: Apipb_Profile,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "UpdateProfile",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func addChild(_ request: Apipb_Child,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "AddChild",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func getChild(_ request: Apipb_GetChildRequest,
                           handler: @escaping (Apipb_Child?, Error?) -> Void) -> GrpcProtoCall<Apipb_Child> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Child, error)
        }
        return RPC(method: "GetChild",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Child.self,
                   responsesWriteable: writable!)
    }
	
    public func updateChild(_ request: Apipb_Child,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "UpdateChild",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func getChildren(_ request: Apipb_GetChildrenFromProfileRequest,
                           handler: @escaping (Apipb_GetChildrenFromProfileResponse?, Error?) -> Void) -> GrpcProtoCall<Apipb_GetChildrenFromProfileResponse> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_GetChildrenFromProfileResponse, error)
        }
        return RPC(method: "GetChildren",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_GetChildrenFromProfileResponse.self,
                   responsesWriteable: writable!)
    }
	
    public func updateGameEntry(_ request: Apipb_GameEntryRequest,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "UpdateGameEntry",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func changeActivation(_ request: Apipb_ChangeChildActivationRequest,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "ChangeActivation",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func getDisabledChildren(_ request: Apipb_GetChildrenFromProfileRequest,
                           handler: @escaping (Apipb_GetChildrenFromProfileResponse?, Error?) -> Void) -> GrpcProtoCall<Apipb_GetChildrenFromProfileResponse> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_GetChildrenFromProfileResponse, error)
        }
        return RPC(method: "GetDisabledChildren",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_GetChildrenFromProfileResponse.self,
                   responsesWriteable: writable!)
    }
	
    public func soundEnable(_ request: Apipb_SoundEnableRequest,
                           handler: @escaping (Apipb_Response?, Error?) -> Void) -> GrpcProtoCall<Apipb_Response> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Response, error)
        }
        return RPC(method: "SoundEnable",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Response.self,
                   responsesWriteable: writable!)
    }
	
    public func updateGameIndices(_ request: Apipb_UpdateIndecesRequest,
                           handler: @escaping (Apipb_Child?, Error?) -> Void) -> GrpcProtoCall<Apipb_Child> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_Child, error)
        }
        return RPC(method: "UpdateGameIndices",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_Child.self,
                   responsesWriteable: writable!)
    }
	
    public func statistics(_ request: Apipb_StatisticsReq,
                           handler: @escaping (Apipb_StatisticsRes?, Error?) -> Void) -> GrpcProtoCall<Apipb_StatisticsRes> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_StatisticsRes, error)
        }
        return RPC(method: "Statistics",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_StatisticsRes.self,
                   responsesWriteable: writable!)
    }
	
}