// Code generated by protoc-gen-grpc-swift
// DO NOT EDIT!
import SwiftProtobuf
import GRPCClient


public class DashboardService: GrpcProtoService {

    public convenience init(host: String) {
        self.init(host: host, packageName: "otsimo", serviceName: "DashboardService")
    }

    public func get(_ request: Otsimo_DashboardGetRequest,
                           handler: @escaping (Otsimo_DashboardItems?, Error?) -> Void) -> GrpcProtoCall<Otsimo_DashboardItems> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_DashboardItems, error)
        }
        return RPC(method: "Get",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_DashboardItems.self,
                   responsesWriteable: writable!)
    }
	
    public func getStream(_ request: Otsimo_DashboardGetRequest,
                           handler: @escaping (Bool, Otsimo_Card?, Error?) -> Void) -> GrpcProtoCall<Otsimo_Card> {
        
        let writable = GRXWriteable { (done, value, error) in
            handler(done, value as? Otsimo_Card, error)
        }

        return RPC(method: "GetStream",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_Card.self,
                   responsesWriteable: writable!)
    }
	
}