// Code generated by protoc-gen-grpc-swift
// DO NOT EDIT!
import SwiftProtobuf
import GRPCClient


public class DashboardProvider: GrpcProtoService {

    public convenience init(host: String) {
        self.init(host: host, packageName: "otsimo", serviceName: "DashboardProvider")
    }

    public func info(_ request: Otsimo_ProviderInfoRequest,
                           handler: @escaping (Otsimo_ProviderInfo?, Error?) -> Void) -> GrpcProtoCall<Otsimo_ProviderInfo> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_ProviderInfo, error)
        }
        return RPC(method: "Info",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_ProviderInfo.self,
                   responsesWriteable: writable!)
    }
	
    public func get(_ request: Otsimo_ProviderGetRequest,
                           handler: @escaping (Otsimo_ProviderItems?, Error?) -> Void) -> GrpcProtoCall<Otsimo_ProviderItems> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_ProviderItems, error)
        }
        return RPC(method: "Get",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_ProviderItems.self,
                   responsesWriteable: writable!)
    }
	
}