// Code generated by protoc-gen-grpc-swift
// DO NOT EDIT!
import SwiftProtobuf
import GRPCClient


public class Discovery: GrpcProtoService {

    public convenience init(host: String) {
        self.init(host: host, packageName: "apipb", serviceName: "Discovery")
    }

    public func get(_ request: Apipb_DiscoveryRequest,
                           handler: @escaping (Apipb_OtsimoServices?, Error?) -> Void) -> GrpcProtoCall<Apipb_OtsimoServices> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Apipb_OtsimoServices, error)
        }
        return RPC(method: "Get",
                   requestsWriter: GRXWriter(value: request),
                   response: Apipb_OtsimoServices.self,
                   responsesWriteable: writable!)
    }
	
}