// Code generated by protoc-gen-grpc-swift
// DO NOT EDIT!
import SwiftProtobuf
import GRPCClient


public class File: GrpcProtoService {

    public convenience init(host: String) {
        self.init(host: host, packageName: "otsimo", serviceName: "File")
    }

    public func storeSmall(_ request: Otsimo_StoreReq,
                           handler: @escaping (Otsimo_StoreRes?, Error?) -> Void) -> GrpcProtoCall<Otsimo_StoreRes> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_StoreRes, error)
        }
        return RPC(method: "StoreSmall",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_StoreRes.self,
                   responsesWriteable: writable!)
    }
	
    public func requestStoreBig(_ request: Otsimo_UploadReq,
                           handler: @escaping (Otsimo_UploadRes?, Error?) -> Void) -> GrpcProtoCall<Otsimo_UploadRes> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_UploadRes, error)
        }
        return RPC(method: "RequestStoreBig",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_UploadRes.self,
                   responsesWriteable: writable!)
    }
	
    public func lookup(_ request: Otsimo_LookupReq,
                           handler: @escaping (Otsimo_LookupRes?, Error?) -> Void) -> GrpcProtoCall<Otsimo_LookupRes> {
        let writable = GRXWriteable { (value, error) in
            handler(value as? Otsimo_LookupRes, error)
        }
        return RPC(method: "Lookup",
                   requestsWriter: GRXWriter(value: request),
                   response: Otsimo_LookupRes.self,
                   responsesWriteable: writable!)
    }
	
}